// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqhmimdhtrgdgniofnwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxaG1pbWRodHJnZGduaW9mbndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MjU3MjcsImV4cCI6MjA3MDIwMTcyN30.LnFvseOaw1EYVJUqcl3V50iZhX419Cuh2sJD-igWYFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});